### ISSUE TITLE
메인화면 디자인 작업

### ISSUE THREAD

**Issue by Jaesang98** [musing-share-music/musing-client#12]
### 설명 ✏️
![image](https://github.com/user-attachments/assets/886f04c0-8159-4e55-8fc0-b92d34604895)
메인화면 디자인 작업내용입니다.

### 기타 👀
1. 수정해야할 사항
  - hotMusic 서브타이틀 폰트 문제
  - 페이지네이션 위치 바꾸기
  - figma랑 똑같이 간격잡았는데 차이가있는문제
  - 음악추천게시판 이미지 수정 필요
  - 추천아티스트 수정 필요

이러한 부분이 아직 문제가 있어 수정이 필요하며, 다음주 까지 진행이 될 수 있을거같습니다!

**Comment by dev-hamster** [comment]
요 내용은 pr에 적는게 더 적합한거 같아용~ 그나저나 손이 진짜 빠르시네요 👍
