### ISSUE TITLE
모달 공통 컴포넌트 

### ISSUE THREAD

**Issue by dev-hamster** [musing-share-music/musing-client#16]
### 설명 ✏️

- 화면 중앙에 띄어지는 ModalBox를 작업합니다.
- 모달이 띄어지면 백그라운드가 어두워집니다.

![스크린샷 2024-12-11 오전 12 37 43](https://github.com/user-attachments/assets/46e83569-2336-40b0-bbf4-2cdbbaa3f5f2)

![스크린샷 2024-12-11 오전 12 57 32](https://github.com/user-attachments/assets/72595e53-2a23-428d-9022-02802ed9b8a5)

### 기타 👀
<!-- 기타 내용을 작성해주세요. -→

**Comment by Jaesang98** [comment]
고생하셨습니다!
