### ISSUE TITLE
메인화면 마무리

### ISSUE THREAD

**Issue by Jaesang98** [musing-share-music/musing-client#17]
### 설명 ✏️
- lint build 에러사항 수정
- 메인화면 작업 마무리
- 각 컴포넌트 type지정
- 이미지와 공통스타일링 share에 추가
![image](https://github.com/user-attachments/assets/8a9970d5-34cf-47e1-b1e6-ce8cff6a8408)
![image](https://github.com/user-attachments/assets/d03515da-87dd-4e9a-bb9b-7c6ef654db6c)

### 기타 👀
우선 진아님이 작성하시는 기준을 따라서 작성중입니다!
굉장히 잘하시네용,,

**Comment by dev-hamster** [comment]
수고하셨습니다 >_<!! 헤헤 감사합니다 고민하면서 작업한 보람이 있네요ㅎㅎ
