### ISSUE TITLE
회원가입 이후 선호 음악 선택 플로우 퍼블리싱

### ISSUE THREAD

**Issue by dev-hamster** [musing-share-music/musing-client#20]
### 설명 ✏️
- 회원가입 이후 사용자가 선호하는 음악을 선택하는 플로우 입니다.

![스크린샷 2024-12-14 오전 12 18 32](https://github.com/user-attachments/assets/e7ec7ca1-d554-41a8-a052-a37d9d26176c)

### 기타 👀
- 필수 선택 플로우로 사용자가 페이지를 이탈해도 이 모달을 띄어줘야 합니다. 이것과 관련해서 새로운 [이슈](https://github.com/musing-share-music/musing-client/issues/21)를 생성해두겠습니다~

**Comment by Jaesang98** [comment]
넵 확인했습니다!
