### ISSUE TITLE
배포된 url에서 새로 고침시 404가 표시

### ISSUE THREAD

**Issue by dev-hamster** [musing-share-music/musing-client#23]
### 설명 ✏️
- 새로고침시 404가 표시됩니다.
- 주소창으로 유효한 라우트로 이동해도 404가 표시됩니다.

<img width="720" alt="스크린샷 2024-12-15 오전 2 05 37" src="https://github.com/user-attachments/assets/91f6a7e3-788c-447f-b7fe-4dd6985f95f4" />

<img width="707" alt="스크린샷 2024-12-15 오전 2 06 19" src="https://github.com/user-attachments/assets/804d95a3-f8e4-455d-85e1-6f25052f9f36" />

### 기타 👀
<!-- 기타 내용을 작성해주세요. -→

**Comment by Jaesang98** [comment]
[chore(jina): json5를 json으로 변환해주는 job 추가
=> 요거 되게 신기하네용!! 고생하셨습니다!
